

query getMatches($matchIds: [Long]!) {
  matches(ids: $matchIds) {
    players {
      hero {
        displayName
        name
      }
      isRadiant
    }
    didRadiantWin
    statsDateTime
    endDateTime
  }
}
