query getMatch($matchId: Long!) {
  match(id: $matchId) {
    players {
      hero {
        displayName
        shortName
      }
      steamAccount {
        id
        name
      }
      isVictory
      isRadiant
      role
      lane
      kills
      deaths
      assists
      goldPerMinute
      experiencePerMinute
    }
  }
}
