name: Build and Publish to NPM registry
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with: 
          node-version: '14'
          check-latest: true

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Get Dependencies if needed
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn workspaces focus --all --production

      - name: Build dist
        run: yarn build

      - name: Archive Build
        uses: actions/upload-artifact@master
        with:
          name: build
          path: |
            dist
            package.json
            package-lock.json
            
  publish:
    needs: build
    name: Publish to Netlify
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download build
        uses: actions/download-artifact@master
        with:
          name: build
      - name: Publish to Netfliy
        uses: nwtgck/actions-netlify@v1.2.2
        with:
          publish-dir: dist
          deploy-messege: "Deployed from Github"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFT_ACCESS_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        